[build]
  command = "npm install" # Install dependensi
  publish = "public"     # Folder statis (jika ada)

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "functions" # Direktori untuk serverless functions
